# Generated by Django 5.2.3 on 2025-07-14 05:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='afternoon',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='night',
        ),
        migrations.AddField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 7, 14)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='time',
            field=models.TimeField(default=datetime.time(11, 5, 49, 963948)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
