# Generated by Django 5.2.3 on 2025-07-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_prescription_afternoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='phone_number',
            field=models.CharField(default=911234567890, help_text='Enter in format +91XXXXXXXXXX', max_length=15),
            preserve_default=False,
        ),
    ]
